#! /bin/sh

case "$1" in
      start)
            wpa_supplicant -iwlan0 -c/etc/wpa_supplicant.conf &
            dhcpcd &
            Device-Controller &
            ;;
      stop)

            ;;
      *)
           echo "Usage: $0 {start|stop}"
           exit 1
esac
exit 0